### ISSUE TITLE
Prompts appear in very dim grey color...

### ISSUE THREAD

**Issue by artemis-prime** [bitriddler/git-change-date#2]
In my terminal window, which is the default setting for Linux Mint... the black bg has an opacity of 90% (ish)... your dk grey text prompts were illegible.  I ran the utility several times without seeing them at all.  I had to go to your docs to figure out what was going on.  Please use a better color.  Blue maybe?

**Comment by kareemaly** [comment]
@artemis-prime thanks for opening an issue, but this is an issue with [prompt](https://github.com/flatiron/prompt) in printing descriptions. Please re-open this issue on their repository.
